### PR TITLE
Initial SK,CZ,RU translation

### PR DESCRIPTION
**Pull request by shajek**

### CODE REVIEW

**Comment by cjaliaga** [comment]
Thanks a lot for the contribution @shajek! For Czech the filename should be "cs.json". Could you please rename that?

**Review by cjaliaga — CHANGES_REQUESTED** [review]
Thanks a lot for the contribution @shajek! For Czech the filename should be "cs.json". Could you please rename that?

**Comment by shajek** [comment]
done :)

**Review by cjaliaga — APPROVED** [review]
Thanks! 🎉

**Pull request merged**
